connect 'jdbc:derby://localhost:1527/cNetBilling;create=true';

DROP TABLE CUSTOMER_INFO;
CREATE TABLE CUSTOMER_INFO (NAME VARCHAR(20) NOT NULL, SURNAME VARCHAR (20), IP_ADDRESS VARCHAR(15));

DROP TABLE IP_COUNTER;
CREATE TABLE IP_COUNTER (IP_ADDRESS VARCHAR (15), TOTAL_DATA DOUBLE, START_DATE TIMESTAMP, END_DATE TIMESTAMP, PORT VARCHAR(10), UPLOAD BOOLEAN);

exit;
--select IP_ADDRESS, sum(total_data), upload from ip_counter group by ip_address, upload;
