CONNECT 'jdbc:derby://localhost:49153/cNetBilling;create=true;user=dbuser;password=dbuser';

-- Creat datauase tables
CREATE TABLE DATAUSAGE
     (
     ID INT NOT NULL GENERATED ALWAYS AS IDENTITY, 
     IP_ADDRESS VARCHAR(15) NOT NULL,
	 BYTES NUMERIC NOT NULL,
	 DATE TIMESTAMP NOT NULL,
	 PORT INTEGER NOT NULL,
	 UPLOAD BOOLEAN NOT NULL,
	 PROTOCOL VARCHAR (5) NOT NULL,
	 PRIMARY KEY (ID));
	 
-- create indexes for the ip address and date
CREATE INDEX IP_ADDR_INDEX ON DATAUSAGE (IP_ADDRESS);
CREATE INDEX DATE_INDEX ON DATAUSAGE (DATE);
CREATE INDEX PROTOCOL_INDEX ON DATAUSAGE (PROTOCOL);

DISCONNECT;
EXIT;